name: build-preview
run-name: build pull request preview

on:
  # run when called from another workflow
  workflow_call:

  # run if user manually requests it
  workflow_dispatch:

# variables
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: read

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Debug dump
        if: runner.debug == '1'
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        if: github.event.action != 'closed'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          allow-unsafe-pr-checkout: true

      - name: Install Ruby packages
        if: github.event.action != 'closed'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Get Pages url
        if: github.event.action != 'closed'
        id: pages
        uses: actions/configure-pages@v4

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Build preview version of site
        if: github.event.action != 'closed'
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}/${{ env.PREVIEWS_FOLDER }}/pr-${{ github.event.number }}"

      - name: Save preview artifact
        run: |
          mkdir -p artifacts
          # save metadata about preview
          printf "%s" "${{ github.event.number }}" > artifacts/number.txt
          printf "%s" "${{ github.event.action }}" > artifacts/action.txt
          # save built preview contents
          if [ -d _site ]; then mv _site artifacts/preview; fi

      # safely save limited artifact from potentially untrusted branch
      - name: Upload preview artifact
        uses: actions/upload-artifact@v7
        with:
          name: preview
          path: artifacts
          retention-days: 1
